# Generated by Django 5.2.7 on 2025-10-25 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('plantel', models.CharField(max_length=50)),
                ('child_name', models.CharField(blank=True, max_length=150)),
                ('grado', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('TUTOR', 'Tutor'), ('ALUMNO', 'Alumno')], max_length=10)),
                ('clave', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
