# Generated by Django 5.2.7 on 2025-11-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('plantel', models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria')], max_length=20)),
                ('child_name', models.CharField(blank=True, max_length=150, null=True)),
                ('grado', models.CharField(blank=True, max_length=120, null=True)),
                ('role', models.CharField(choices=[('ACOMPAÑANTE HOMBRE', 'Acompañante Hombres'), ('ACOMPAÑANTE MUJER', 'Acompañante Mujer'), ('ABUELITO', 'Abuelito'), ('ABUELITA', 'Abuelita'), ('ALUMNOS LMA BAJAH', 'ALUMNOS LMA Primaria (primaria baja hombres 1°, 2° y 3°)'), ('ALUMNOS LMA BAJAM', 'ALUMNOS LMA Primaria (primaria baja mujeres 1°, 2° y 3°)'), ('ALUMNOS LMA ALTAM', 'ALUMNOS LMA Primaria (primaria alta mujeres 4°, 5° y 6°)'), ('ALUMNOS LMA ALTAH', 'ALUMNOS LMA Primaria (primaria alta hombres 4°, 5° y 6°)'), ('ALUMNOS LMA SECH', 'ALUMNOS LMA Secundaria (hombres)'), ('ALUMNOS LMA SECM', 'ALUMNOS LMA Secundaria (mujeres)'), ('ALUMNOS LMA PREPH', 'ALUMNOS LMA Preparatoria (hombres)'), ('ALUMNOS LMA PREPM', 'ALUMNOS LMA Preparatoria (mujeres)')], max_length=40)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clave', models.CharField(blank=True, editable=False, max_length=40, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
