# Generated by Django 5.2.3 on 2025-10-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='child_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='clave',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='grado',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='plantel',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('ACOMPAÑANTE HOMBRE', 'Acompañante Hombre'), ('ACOMPAÑANTE MUJER', 'Acompañante Mujer'), ('ABUELITO', 'Abuelito'), ('ABUELITA', 'Abuelita'), ('TUTOR', 'Tutor / Otro tutor'), ('ALUMNO', 'Alumno')], max_length=50),
        ),
    ]
