# Generated by Django 5.2.7 on 2025-11-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0002_alter_participant_child_name_alter_participant_clave_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='participant',
            name='child_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='participant',
            name='clave',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='participant',
            name='grado',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='participant',
            name='plantel',
            field=models.CharField(choices=[('Primaria', 'Primaria'), ('Secundaria', 'Secundaria'), ('Preparatoria', 'Preparatoria')], max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('ALUMNO', 'Alumno'), ('TUTOR', 'Tutor'), ('ACOMPAÑANTE HOMBRE', 'Acompañante Hombre'), ('ACOMPAÑANTE MUJER', 'Acompañante Mujer'), ('ABUELITO', 'Abuelito'), ('ABUELITA', 'Abuelita')], max_length=25),
        ),
    ]
