# Generated by Django 5.2.7 on 2025-11-06 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0003_remove_participant_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('ALUMNO', 'Alumno'), ('TUTOR', 'Tutor'), ('ACOMPAÑANTE HOMBRE', 'Acompañante Hombre'), ('ACOMPAÑANTE MUJER', 'Acompañante Mujer'), ('ABUELITO', 'Abuelito'), ('ABUELITA', 'Abuelita')], max_length=30),
        ),
    ]
