# Generated by Django 5.2.7 on 2025-11-07 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0004_alter_participant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
           # preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['plantel'], name='registro_pa_plantel_9a8eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['clave'], name='registro_pa_clave_3c2e8b_idx'),
        ),
        migrations.AddIndex(
            model_name='participant',
            index=models.Index(fields=['full_name'], name='registro_pa_full_na_91e27d_idx'),
        ),
    ]
