# Generated by Django 5.2.7 on 2025-11-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0006_participant_updated_at_alter_participant_created_at'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='participant',
            name='registro_pa_plantel_9a8eb3_idx',
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='registro_pa_clave_3c2e8b_idx',
        ),
        migrations.RemoveIndex(
            model_name='participant',
            name='registro_pa_full_na_91e27d_idx',
        ),
        migrations.AlterField(
            model_name='participant',
            name='child_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='clave',
            field=models.CharField(blank=True, editable=False, max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='full_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='participant',
            name='grado',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='role',
            field=models.CharField(choices=[('ACOMPAÑANTE HOMBRE', 'Acompañante Hombres'), ('ACOMPAÑANTE MUJER', 'Acompañante Mujer'), ('ABUELITO', 'Abuelito'), ('ABUELITA', 'Abuelita'), ('ALUMNOS LMA BAJAH', 'ALUMNOS LMA Primaria (primaria baja hombres 1°, 2° y 3°)'), ('ALUMNOS LMA BAJAM', 'ALUMNOS LMA Primaria (primaria baja mujeres 1°, 2° y 3°)'), ('ALUMNOS LMA ALTAM', 'ALUMNOS LMA Primaria (primaria alta mujeres 4°, 5° y 6°)'), ('ALUMNOS LMA ALTAH', 'ALUMNOS LMA Primaria (primaria alta hombres 4°, 5° y 6°)'), ('ALUMNOS LMA SECH', 'ALUMNOS LMA Secundaria (hombres)'), ('ALUMNOS LMA SECM', 'ALUMNOS LMA Secundaria (mujeres)'), ('ALUMNOS LMA PREPH', 'ALUMNOS LMA Preparatoria (hombres)'), ('ALUMNOS LMA PREPM', 'ALUMNOS LMA Preparatoria (mujeres)')], max_length=40),
        ),
    ]
