# Generated by Django 5.2.7 on 2025-11-12 04
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("registro", "0006_lo_que_tengas_antes"),  # <-- deja la dependencia que tenías
    ]

    operations = [
        # Paso 1: permitir NULL y sin unique aún
        migrations.AlterField(
            model_name="participant",
            name="clave",
            field=models.CharField(
                max_length=40,
                null=True,
                blank=True,
                editable=False,
            ),
        ),
        # Paso 2: limpiar datos existentes ('' -> NULL)
        migrations.RunSQL(
            sql="UPDATE registro_participant SET clave = NULL WHERE clave = ''",
            reverse_sql="",
        ),
        # Paso 3: ahora sí, activar unique
        migrations.AlterField(
            model_name="participant",
            name="clave",
            field=models.CharField(
                max_length=40,
                unique=True,
                null=True,
                blank=True,
                editable=False,
            ),
        ),
    ]
